#!/usr/bin/perl

use Mojo::Base -strict;
use Curses;

use lib 'lib';
use App::termpub;
use App::termpub::Epub;

initscr;
noecho;
cbreak;
curs_set(0);

for my $filename (@ARGV) {

    my $epub = eval { App::termpub::Epub->new( filename => $filename ) };

    if ( !$epub ) {
        warn "$@\n";
        next;
    }

    App::termpub->new( epub => $epub )->run;
}

END {
    endwin;
}

exit 0;

__END__

=pod

=head1 NAME

App::termpub - read epubs in the terminal

=head1 SYNOPSIS

termpub I<file>...

=head1 DESCRIPTION

termpub is a I<terminal> viewer for epubs. At startup termpub displays
the first chapter with real content if possible.

=head1 KEY BINDINGS

=over 4

=item h, ?

Display help screen.

=item n

Go to the next chapter.

=item p

Go to the previous chapter.

=item [num] g

Go to line I<num> in the file, default 1.

=item [num] G

Go to line I<num> in the file, default the end of the file.

=item C-g

Cancel I<num> argument for I<g> or I<G>.

=item KEY_DOWN, j

Scroll one line down.

=item KEY_UP, k

Scroll one line up.

=item KEY_NPAGE, SPACE

Scroll forward one window.

=item KEY_PPAGE, KEY_BACKSPACE

Scroll backward one window.

=item KEY_HOME

Go to the beginning of the current chapter.

=item KEY_END

Go to the ned of the current chapter.

=item q

Quit.

=back

=head1 INSTALLATION

If you have cpanminus installed, you can simply install this program
by calling

  $ cpanm .

Otherwise you can build a standalone script with

  $ ./build-standalone

and copy the generated script I<termpub> somewhere in your path. In this
case you need to installed the dependencies yourself. Termpub depends
on the perl modules Mojolicious, Curses and Archive::Zip. On Debian the
following command will install these packages.

  $ apt-get install libmojolicious-perl libcurses-perl libarchive-zip-perl

=head1 COPYRIGHT AND LICENSE 

Copyright 2019 Mario Domgoergen C<< <mario@domgoergen.com> >> 

This program is free software: you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by 
the Free Software Foundation, either version 3 of the License, or 
(at your option) any later version. 

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details. 

You should have received a copy of the GNU General Public License 
along with this program.  If not, see <http://www.gnu.org/licenses/>. 

=cut
